# Generated by Django 5.0.6 on 2024-08-29 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('POLITICAL', 'Political'), ('ENTERTAINMENT', 'Entertainment'), ('ECONOMICS', 'Economics'), ('EDUCATION', 'Education'), ('SCIENCE', 'Science'), ('SPORTS', 'Sports'), ('INTERNATIONAL', 'International'), ('COOKING', 'Cooking'), ('WEATHER', 'Weather'), ('TECH', 'Tech')], max_length=100)),
                ('content', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
