# Generated by Django 5.0.6 on 2024-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
